modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="create_unrestricted_vault"
version="\${version}"
displayName="Create: Unrestricted Vault"
authors="Aether_254"
description='''Makes Create Item Vault width and length limits configurable and adds optional vertical Item Vaults without changing Vault Capability.'''

[[dependencies.create_unrestricted_vault]]
modId="forge"
mandatory=true
versionRange="[47.1.33,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_unrestricted_vault]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_unrestricted_vault]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_unrestricted_vault]]
modId="cloth_config"
mandatory=true
versionRange="[11.1.136,)"
ordering="AFTER"
side="BOTH"

