modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_unrestricted_vault"
version="\${version}"
displayName="Create: Unrestricted Vault"
authors="Aether_254"
description='''Makes Create Item Vault width and length limits configurable and adds optional vertical Item Vaults without changing Vault Capability.'''

[[mixins]]
config="create_unrestricted_vault.mixins.json"

[[dependencies.create_unrestricted_vault]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_unrestricted_vault]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_unrestricted_vault]]
modId="create"
type="required"
versionRange="[6.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_unrestricted_vault]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"

